#!/bin/bash

set -e

if [ "$#" -ne 3 ]; then
	echo "usage: mkSrcTarball <binPath> <imseqDir> <targetDir>" >&2
	exit 1;
fi

binPath="$1"
imseqDir="$2"
targetDir="$3"

if [ -e "$targetDir" ]; then
	echo "ERROR: Target directory exists" >&2
	exit 2;
fi

# Create the target directory
mkdir "$targetDir"
cd "$targetDir"

# Copy the necessary files
cp -rv "$imseqDir"/Homo.Sapiens.???.fa "$imseqDir"/LICENSE "$imseqDir"/examples "$imseqDir"/util/bin-tarball/* "$binPath" .
cd ..
