#!/bin/bash

set -e

if [ "$#" -ne 3 ]; then
	echo "usage: mkSrcTarball <seqanDir> <imseqDir> <targetDir>" >&2
	exit 1;
fi

seqanDir="$1"
imseqDir="$2"
targetDir="$3"

if [ -e "$targetDir" ]; then
	echo "ERROR: Target directory exists" >&2
	exit 2;
fi

# Create the target directory
oldDir="$PWD"

mkdir "$targetDir"
cd "$targetDir"

# Copy the reduced SeqAn source tree
rsync -aq \
	--exclude ".git*" \
	--exclude "/apps" \
	--exclude "/demos" \
	--exclude "/tests" \
	--exclude "/dox" \
	--exclude "/manual" \
	--include "/util/cmake" \
	--exclude "/util/*" \
	--safe-links "$seqanDir"/ seqan_minimal

# Fix CMakeLists.txt
cd seqan_minimal
mv CMakeLists.txt CMakeLists.txt~
egrep -v 'add_subdirectory|message..STATUS..Configuring' CMakeLists.txt~ > CMakeLists.txt
rm -f CMakeLists.txt~
sed -i '' -e 's%^..Include Subdirectories%&\
add_subdirectory(../imseq imseq-build)%' CMakeLists.txt
cd ..

# Copy the IMSEQ source tree
rsync -aq --exclude ".git*" "$imseqDir"/ imseq
mv imseq/util/src-tarball/* .
mv imseq/examples .
mv imseq/*.fa .
rm -rf imseq/util

cd "$oldDir"

